INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('乳白色', '255,251,240', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('白色', '255,255,255', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('米白色', '238,222,176', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅灰色', '228,228,228', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('深灰色', '102,102,102', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('灰色', '128,128,128', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('银色', '192,192,192', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('黑色', '0,0,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('桔红色', '255,117,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('玫红色', '223,27,118', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('粉红色', '255,182,193', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('红色', '255,0,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('藕色', '238,208,216', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('西瓜红', '240,86,84', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('酒红色', '153,0,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('卡其色', '195,176,145', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('姜黄色', '255,199,115', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('明黄色', '255,255,1', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('杏色', '247,238,214', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('柠檬黄', '255, 236, 67', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('桔色', '255,165,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅黄色', '250,255,114', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('荧光黄', '234,255,86', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('金色', '255,215,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('香槟色', '255,249,177', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('黄色', '255,255,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('军绿色', '93,118,42', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('墨绿色', '66,204,33', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅绿色', '152,251,152', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('绿色', '0,128,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('翠绿色', '10,163,68', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('荧光绿', '35,250,7', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('青色', '0,224,158', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('天蓝色', '68,206,246', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('孔雀蓝', '0,164,197', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('宝蓝色', '75,92,196', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅蓝色', '210,240,244', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('深蓝色', '4,22,144', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('湖蓝色', '48,223,243', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('蓝色', '0,0,254', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('藏青色', '46,78,126', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅紫色', '237,224,230', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('深紫色', '67,6,83', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('紫红色', '139,0,98', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('紫罗兰', '183,172,228', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('紫色', '128,0,128', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('咖啡色', '96,57,18', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('巧克力色', '96,57,18', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('栗色', '96,40,30', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('浅棕色', '179,92,68', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('深卡其布色', '189,183,107', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('深棕色', '124,75,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('褐色', '133,91,0', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('驼色', '168,132,98', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('花色', '255,255,255', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('透明', '255,255,255', 1, null, null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('S', null, 2, '2016-06-17 09:59:39', '2016-06-17 15:33:27', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('M', null, 2, '2016-06-17 09:59:52', '2016-06-17 15:33:27', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('L', null, 2, '2016-06-17 09:59:52', '2016-06-17 15:33:27', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('XL', null, 2, '2016-06-17 09:59:52', '2016-06-17 15:33:27', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('1G', null, 3, '2016-06-17 10:00:12', null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('2G', null, 3, '2016-06-17 10:00:12', null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('4G', null, 3, '2016-06-17 10:00:12', null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('8G', null, 3, '2016-06-17 10:00:12', null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('均码', null, 2, '2016-06-17 15:33:27', null, 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('1', null, 4, '2016-07-15 14:36:19', '2016-07-15 14:37:06', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('2', null, 4, '2016-07-15 14:36:19', '2016-07-15 14:37:06', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('3', null, 4, '2016-07-15 14:36:46', '2016-07-15 14:37:06', 1);
INSERT INTO mingshop.qi_format_value (name, remark, format_id, date_add, date_edit, status) VALUES ('4', null, 4, '2016-07-15 14:36:30', '2016-07-15 14:37:06', 1);